baseURL: "http://localhost:1313/"

outputs:
  home: ["HTML", "RSS"]
  page: ["HTML", "SearchIndex"]
  section: ["HTML", "RSS", "SearchIndex"]
  taxonomy: ["HTML", "RSS"]
  term: ["HTML", "RSS"]
  search: ["HTML", "SearchIndex"]

taxonomies:
  kategoriat: "kategoriat"
  tagit: "tagit"

outputFormats:
  SearchIndex:
    mediaType: application/json
    baseName: search-index-slim
    isPlainText: true
    notAlternative: true

mediaTypes:
  application/json:
    suffixes: ['json']
